/* ==========================================================================
   i18n.js — shared translation dictionary + language switcher
   Used by index.html, mpc-sample-kit-creator.html and checkout.html.

   How it works:
   - TRANSLATIONS holds one entry per key, with a value for every language.
   - Elements marked data-i18n="key"            -> textContent is replaced
   - Elements marked data-i18n-html="key"        -> innerHTML is replaced (key's value may contain safe inline HTML like <strong>/<a>)
   - Elements marked data-i18n-placeholder="key" -> placeholder attribute is replaced
   - Elements marked data-i18n-aria="key"        -> aria-label attribute is replaced
   - window.I18N exposes { t, getLang, applyLang, LANGS } for page-specific
     scripts (the screenshot gallery, the checkout page's dynamic text) that
     need to build translated strings themselves.
   - A "langchange" event fires on document whenever the language changes,
     so page scripts can re-render anything they built dynamically.

   To add a new language: add it to LANGS below, then add its code as a key
   to every entry in TRANSLATIONS (missing keys silently fall back to English).
   To add a new translatable string: add a key to TRANSLATIONS, then add
   data-i18n="that.key" to the element in the HTML.
   ========================================================================== */

(function () {

  var LANGS = [
    { code: 'en', label: 'English', flag: '🇬🇧' },
    { code: 'it', label: 'Italiano', flag: '🇮🇹' },
    { code: 'es', label: 'Español', flag: '🇪🇸' },
    { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
    { code: 'fr', label: 'Français', flag: '🇫🇷' },
    { code: 'zh', label: '中文', flag: '🇨🇳' },
    { code: 'ru', label: 'Русский', flag: '🇷🇺' }
  ];

  var TRANSLATIONS = {

    /* ---------- common (shared across pages) ---------- */
    'common.themeToggle': { en: 'Toggle dark mode', it: 'Attiva/disattiva tema scuro', es: 'Activar/desactivar modo oscuro', de: 'Dunkelmodus umschalten', fr: 'Activer/désactiver le mode sombre', zh: '切换深色模式', ru: 'Переключить тёмную тему' },
    'common.langSwitcher': { en: 'Choose language', it: 'Scegli lingua', es: 'Elegir idioma', de: 'Sprache wählen', fr: 'Choisir la langue', zh: '选择语言', ru: 'Выбрать язык' },
    'common.catalog': { en: 'Catalog', it: 'Catalogo', es: 'Catálogo', de: 'Katalog', fr: 'Catalogue', zh: '目录', ru: 'Каталог' },
    'common.backCatalog': { en: '← Catalog', it: '← Catalogo', es: '← Catálogo', de: '← Katalog', fr: '← Catalogue', zh: '← 目录', ru: '← Каталог' },
    'common.backToCatalog': { en: '← Back to catalog', it: '← Torna al catalogo', es: '← Volver al catálogo', de: '← Zurück zum Katalog', fr: '← Retour au catalogue', zh: '← 返回目录', ru: '← Назад в каталог' },
    'common.backToProduct': { en: '← Back to product page', it: '← Torna alla pagina del prodotto', es: '← Volver a la página del producto', de: '← Zurück zur Produktseite', fr: '← Retour à la page produit', zh: '← 返回产品页面', ru: '← Назад на страницу продукта' },
    'common.back': { en: '← Back', it: '← Indietro', es: '← Volver', de: '← Zurück', fr: '← Retour', zh: '← 返回', ru: '← Назад' },
    'common.goToSlide': { en: 'Go to slide {n}', it: 'Vai alla slide {n}', es: 'Ir a la diapositiva {n}', de: 'Zu Folie {n} wechseln', fr: 'Aller à la diapositive {n}', zh: '前往幻灯片 {n}', ru: 'Перейти к слайду {n}' },
    'common.buyNow': { en: 'Buy Now', it: 'Acquista ora', es: 'Comprar ahora', de: 'Jetzt kaufen', fr: 'Acheter maintenant', zh: '立即购买', ru: 'Купить сейчас' },

    /* ---------- nav ---------- */
    'nav.info': { en: 'Info', it: 'Info', es: 'Información', de: 'Info', fr: 'Infos', zh: '关于', ru: 'Инфо' },
    'nav.browseCatalog': { en: 'Browse catalog', it: 'Sfoglia il catalogo', es: 'Ver catálogo', de: 'Katalog durchsuchen', fr: 'Parcourir le catalogue', zh: '浏览目录', ru: 'Смотреть каталог' },
    'nav.features': { en: 'Features', it: 'Funzioni', es: 'Funciones', de: 'Funktionen', fr: 'Fonctionnalités', zh: '功能', ru: 'Функции' },
    'nav.screenshots': { en: 'Screenshots', it: 'Screenshot', es: 'Capturas', de: 'Screenshots', fr: 'Captures d’écran', zh: '截图', ru: 'Скриншоты' },
    'nav.buy': { en: 'Buy', it: 'Acquista', es: 'Comprar', de: 'Kaufen', fr: 'Acheter', zh: '购买', ru: 'Купить' },

    /* ---------- index.html ---------- */
    'index.hero.kicker': { en: 'Independent software', it: 'Software indipendente', es: 'Software independiente', de: 'Unabhängige Software', fr: 'Logiciel indépendant', zh: '独立软件', ru: 'Независимое ПО' },
    'index.hero.title': { en: 'Tools I build for people who make music.', it: 'Strumenti che creo per chi fa musica.', es: 'Herramientas que creo para quienes hacen música.', de: 'Tools, die ich für Musikschaffende baue.', fr: 'Des outils que je conçois pour les musiciens.', zh: '为音乐制作人打造的工具。', ru: 'Инструменты, которые я создаю для музыкантов.' },
    'index.hero.lead': { en: 'This is where I collect the software I develop for my own production workflow: small tools designed to solve real problems, without the fluff. Every project has its own page, with what it does and what it’s actually for.', it: 'Qui raccolgo il software che sviluppo per il mio flusso di produzione: piccoli strumenti pensati per risolvere problemi reali, senza fronzoli. Ogni progetto ha una pagina dedicata, con cosa fa e a cosa serve davvero.', es: 'Aquí reúno el software que desarrollo para mi propio flujo de producción: pequeñas herramientas pensadas para resolver problemas reales, sin adornos. Cada proyecto tiene su propia página, con lo que hace y para qué sirve realmente.', de: 'Hier sammle ich die Software, die ich für meinen eigenen Produktions-Workflow entwickle: kleine Tools, die echte Probleme lösen sollen, ohne Schnickschnack. Jedes Projekt hat eine eigene Seite mit dem, was es tut und wofür es wirklich gedacht ist.', fr: 'C’est ici que je rassemble les logiciels que je développe pour mon propre flux de production : de petits outils conçus pour résoudre de vrais problèmes, sans fioritures. Chaque projet a sa propre page, avec ce qu’il fait et à quoi il sert vraiment.', zh: '这里收录了我为自己的制作流程开发的软件：为解决实际问题而设计的小工具，没有多余的花哨功能。每个项目都有自己的页面，说明它的功能和真正用途。', ru: 'Здесь собрано программное обеспечение, которое я разрабатываю для собственного рабочего процесса: небольшие инструменты, созданные для решения реальных задач, без лишнего. У каждого проекта своя страница с описанием того, что он делает и для чего на самом деле нужен.' },
    'index.catalog.title': { en: 'Catalog', it: 'Catalogo', es: 'Catálogo', de: 'Katalog', fr: 'Catalogue', zh: '目录', ru: 'Каталог' },
    'index.catalog.subtitle': { en: 'Software available right now.', it: 'Software disponibile da subito.', es: 'Software disponible ahora mismo.', de: 'Software, die jetzt verfügbar ist.', fr: 'Logiciels disponibles dès maintenant.', zh: '现已可用的软件。', ru: 'ПО, доступное прямо сейчас.' },
    'index.product.desc': { en: 'Convert libraries, generate 16-pad kits in seconds, and organize your sample archive for MPC.', it: 'Converti librerie, genera kit a 16 pad in pochi secondi e organizza il tuo archivio sample per MPC.', es: 'Convierte librerías, genera kits de 16 pads en segundos y organiza tu archivo de samples para MPC.', de: 'Bibliotheken konvertieren, in Sekunden 16-Pad-Kits erzeugen und dein Sample-Archiv für den MPC organisieren.', fr: 'Convertissez vos librairies, générez des kits 16 pads en quelques secondes et organisez votre archive de samples pour MPC.', zh: '转换音色库，几秒钟内生成 16 键垫套件，并整理你的 MPC 样本档案。', ru: 'Конвертируйте библиотеки, создавайте 16-пэдовые киты за секунды и упорядочивайте архив сэмплов для MPC.' },
    'index.product.tag1': { en: 'Kit builder · MPC', it: 'Kit builder · MPC', es: 'Creador de kits · MPC', de: 'Kit-Builder · MPC', fr: 'Créateur de kits · MPC', zh: '套件生成 · MPC', ru: 'Сборка китов · MPC' },
    'index.product.tag2': { en: 'macOS & Windows', it: 'macOS e Windows', es: 'macOS y Windows', de: 'macOS & Windows', fr: 'macOS et Windows', zh: 'macOS 与 Windows', ru: 'macOS и Windows' },
    'index.comingSoon.title': { en: 'Coming soon', it: 'In arrivo', es: 'Próximamente', de: 'Demnächst', fr: 'Bientôt disponible', zh: '即将推出', ru: 'Скоро' },
    'index.comingSoon.desc': { en: 'New tools in the works. Check back soon.', it: 'Nuovi strumenti in lavorazione. Torna a trovarmi presto.', es: 'Nuevas herramientas en camino. Vuelve pronto.', de: 'Neue Tools sind in Arbeit. Schau bald wieder vorbei.', fr: 'De nouveaux outils sont en préparation. Repassez bientôt.', zh: '新工具正在开发中，敬请期待。', ru: 'Новые инструменты в разработке. Загляните позже.' },
    'index.info.title': { en: 'Info', it: 'Info', es: 'Información', de: 'Info', fr: 'Infos', zh: '关于', ru: 'Инфо' },
    'index.info.subtitle': { en: 'Who’s behind these tools.', it: 'Chi c’è dietro questi strumenti.', es: 'Quién está detrás de estas herramientas.', de: 'Wer hinter diesen Tools steckt.', fr: 'Qui se cache derrière ces outils.', zh: '这些工具背后的人。', ru: 'Кто стоит за этими инструментами.' },
    'index.info.card1.title': { en: 'What you’ll find here', it: 'Cosa trovi qui', es: 'Qué encontrarás aquí', de: 'Was dich hier erwartet', fr: 'Ce que vous trouverez ici', zh: '你能在这里找到什么', ru: 'Что вы здесь найдёте' },
    'index.info.card1.desc': { en: 'Software designed and built for practical use in music production: sample management, kit building, automating repetitive work. Every tool starts from a real need — mine, first of all.', it: 'Software progettato e costruito per un uso pratico nella produzione musicale: gestione dei sample, costruzione di kit, automazione del lavoro ripetitivo. Ogni strumento nasce da un bisogno reale — il mio, prima di tutto.', es: 'Software diseñado y construido para un uso práctico en la producción musical: gestión de samples, creación de kits, automatización del trabajo repetitivo. Cada herramienta nace de una necesidad real — la mía, antes que nada.', de: 'Software, die für den praktischen Einsatz in der Musikproduktion entwickelt wurde: Sample-Verwaltung, Kit-Erstellung, Automatisierung sich wiederholender Arbeit. Jedes Tool entsteht aus einem echten Bedürfnis — zuallererst meinem eigenen.', fr: 'Des logiciels conçus pour un usage pratique dans la production musicale : gestion des samples, création de kits, automatisation des tâches répétitives. Chaque outil part d’un vrai besoin — le mien, avant tout.', zh: '专为音乐制作实际需求而设计开发的软件：样本管理、套件构建、重复性工作自动化。每个工具都源于一个真实的需求——首先是我自己的需求。', ru: 'Программы, созданные для практического применения в музыкальном продакшене: управление сэмплами, сборка китов, автоматизация рутинной работы. Каждый инструмент рождается из реальной потребности — прежде всего моей собственной.' },
    'index.info.card2.title': { en: 'Updates', it: 'Aggiornamenti', es: 'Actualizaciones', de: 'Updates', fr: 'Mises à jour', zh: '更新', ru: 'Обновления' },
    'index.info.card2.desc': { en: 'The catalog grows over time: new tools get added as I finish them. If you’re interested in one of these projects, get in touch.', it: 'Il catalogo cresce nel tempo: nuovi strumenti vengono aggiunti man mano che li completo. Se sei interessato a uno di questi progetti, scrivimi.', es: 'El catálogo crece con el tiempo: se añaden nuevas herramientas a medida que las termino. Si te interesa alguno de estos proyectos, escríbeme.', de: 'Der Katalog wächst mit der Zeit: Neue Tools kommen hinzu, sobald ich sie fertigstelle. Wenn dich eines dieser Projekte interessiert, melde dich gerne.', fr: 'Le catalogue s’enrichit au fil du temps : de nouveaux outils sont ajoutés au fur et à mesure. Si l’un de ces projets vous intéresse, contactez-moi.', zh: '目录会不断扩充：新工具完成后会陆续加入。如果你对其中某个项目感兴趣，欢迎联系我。', ru: 'Каталог со временем растёт: новые инструменты добавляются по мере готовности. Если вас заинтересовал один из проектов, напишите мне.' },
    'index.contact.emailPlaceholder': { en: 'you@example.com', it: 'tu@esempio.com', es: 'tu@ejemplo.com', de: 'du@beispiel.com', fr: 'vous@exemple.com', zh: 'you@example.com', ru: 'you@example.com' },

    /* ---------- mpc-sample-kit-creator.html ---------- */
    'product.hero.kicker': { en: 'Kit builder · MPC', it: 'Kit builder · MPC', es: 'Creador de kits · MPC', de: 'Kit-Builder · MPC', fr: 'Créateur de kits · MPC', zh: '套件生成 · MPC', ru: 'Сборка китов · MPC' },
    'product.hero.lead': { en: 'Everything you need to build, convert and organize your MPC kits, in one program for macOS and Windows. Bring the libraries you already own into your MPC and generate 16-pad kits from your own samples in seconds.', it: 'Tutto ciò che ti serve per costruire, convertire e organizzare i tuoi kit MPC, in un unico programma per macOS e Windows. Porta nel tuo MPC le librerie che già possiedi e genera kit a 16 pad dai tuoi sample in pochi secondi.', es: 'Todo lo que necesitas para crear, convertir y organizar tus kits de MPC, en un solo programa para macOS y Windows. Lleva a tu MPC las librerías que ya tienes y genera kits de 16 pads a partir de tus propios samples en segundos.', de: 'Alles, was du brauchst, um deine MPC-Kits zu bauen, zu konvertieren und zu organisieren — in einem Programm für macOS und Windows. Bring die Bibliotheken, die du bereits besitzt, in deinen MPC und erzeuge in Sekunden 16-Pad-Kits aus deinen eigenen Samples.', fr: 'Tout ce dont vous avez besoin pour créer, convertir et organiser vos kits MPC, dans un seul programme pour macOS et Windows. Importez dans votre MPC les librairies que vous possédez déjà et générez des kits 16 pads à partir de vos propres samples en quelques secondes.', zh: '一款适用于 macOS 和 Windows 的程序，助你构建、转换和整理 MPC 套件。将你已有的音色库导入 MPC，几秒钟内即可用你自己的样本生成 16 键垫套件。', ru: 'Всё необходимое для сборки, конвертации и организации китов MPC — в одной программе для macOS и Windows. Перенесите уже имеющиеся у вас библиотеки в MPC и создавайте 16-пэдовые киты из собственных сэмплов за секунды.' },
    'product.meta.macwin': { en: 'macOS & Windows', it: 'macOS e Windows', es: 'macOS y Windows', de: 'macOS & Windows', fr: 'macOS et Windows', zh: 'macOS 与 Windows', ru: 'macOS и Windows' },
    'product.meta.akai': { en: 'Akai XPM → MPC Sample', it: 'Akai XPM → MPC Sample', es: 'Akai XPM → MPC Sample', de: 'Akai XPM → MPC Sample', fr: 'Akai XPM → MPC Sample', zh: 'Akai XPM → MPC Sample', ru: 'Akai XPM → MPC Sample' },
    'product.meta.maschine': { en: 'Maschine → MPC Sample', it: 'Maschine → MPC Sample', es: 'Maschine → MPC Sample', de: 'Maschine → MPC Sample', fr: 'Maschine → MPC Sample', zh: 'Maschine → MPC Sample', ru: 'Maschine → MPC Sample' },
    'product.meta.ableton': { en: 'Ableton Drum Rack → MPC Sample', it: 'Ableton Drum Rack → MPC Sample', es: 'Ableton Drum Rack → MPC Sample', de: 'Ableton Drum Rack → MPC Sample', fr: 'Ableton Drum Rack → MPC Sample', zh: 'Ableton Drum Rack → MPC Sample', ru: 'Ableton Drum Rack → MPC Sample' },
    'product.meta.kitgen': { en: '16-pad kit generation', it: 'Generazione kit a 16 pad', es: 'Generación de kits de 16 pads', de: '16-Pad-Kit-Erzeugung', fr: 'Génération de kits 16 pads', zh: '16 键垫套件生成', ru: 'Генерация 16-пэдовых китов' },
    'product.meta.archive': { en: 'Personal sample archive', it: 'Archivio sample personale', es: 'Archivo personal de samples', de: 'Persönliches Sample-Archiv', fr: 'Archive de samples personnelle', zh: '个人样本档案', ru: 'Личный архив сэмплов' },
    'product.btn.seeWhatItDoes': { en: 'See what it does', it: 'Scopri cosa fa', es: 'Descubre qué hace', de: 'Funktionen ansehen', fr: 'Découvrir les fonctionnalités', zh: '了解功能详情', ru: 'Что умеет программа' },
    'product.screenshots.title': { en: 'One app, three superpowers', it: 'Un’app, tre superpoteri', es: 'Una app, tres superpoderes', de: 'Eine App, drei Superkräfte', fr: 'Une app, trois super-pouvoirs', zh: '一款应用，三大超能力', ru: 'Одно приложение — три суперспособности' },
    'product.screenshots.subtitle': { en: 'Convert, generate, customize — see it in motion.', it: 'Converti, genera, personalizza — guardalo in azione.', es: 'Convierte, genera, personaliza — míralo en acción.', de: 'Konvertieren, erzeugen, anpassen — sieh es in Aktion.', fr: 'Convertir, générer, personnaliser — à voir en action.', zh: '转换、生成、自定义——看它如何运作。', ru: 'Конвертация, генерация, настройка — посмотрите в действии.' },
    'product.features.title': { en: 'What it does', it: 'Cosa fa', es: 'Qué hace', de: 'Was es kann', fr: 'Ce qu’il fait', zh: '功能一览', ru: 'Что умеет программа' },
    'product.features.subtitle': { en: 'From the libraries you already own to kits ready for the hardware.', it: 'Dalle librerie che già possiedi a kit pronti per l’hardware.', es: 'Desde las librerías que ya tienes hasta kits listos para el hardware.', de: 'Von deinen bereits vorhandenen Bibliotheken bis zu hardware-fertigen Kits.', fr: 'De vos librairies existantes aux kits prêts pour le matériel.', zh: '从你已有的音色库到可直接用于硬件的套件。', ru: 'От уже имеющихся у вас библиотек до китов, готовых к загрузке в железо.' },

    'product.feature1.title': { en: 'Convert the libraries you already own', it: 'Converti le librerie che già possiedi', es: 'Convierte las librerías que ya tienes', de: 'Konvertiere deine vorhandenen Bibliotheken', fr: 'Convertissez vos librairies existantes', zh: '转换你已有的音色库', ru: 'Конвертируйте уже имеющиеся библиотеки' },
    'product.feature1.body': { en: 'You don’t need to start from scratch. Bring the kits you’ve already built elsewhere into your MPC: native Akai <strong>.xpm</strong> kits, Native Instruments Maschine (<strong>.mxgrp</strong>, Kitmaker and Maschine programs), and Ableton Live Drum Racks (<strong>.adg</strong>).', it: 'Non devi ripartire da zero. Porta nel tuo MPC i kit che hai già costruito altrove: kit nativi Akai <strong>.xpm</strong>, Native Instruments Maschine (<strong>.mxgrp</strong>, programmi Kitmaker e Maschine) e Ableton Live Drum Rack (<strong>.adg</strong>).', es: 'No hace falta empezar de cero. Lleva a tu MPC los kits que ya has creado en otros programas: kits nativos Akai <strong>.xpm</strong>, Native Instruments Maschine (<strong>.mxgrp</strong>, programas Kitmaker y Maschine) y Ableton Live Drum Racks (<strong>.adg</strong>).', de: 'Du musst nicht bei null anfangen. Bring die Kits, die du bereits anderswo erstellt hast, in deinen MPC: native Akai-<strong>.xpm</strong>-Kits, Native Instruments Maschine (<strong>.mxgrp</strong>, Kitmaker- und Maschine-Programme) sowie Ableton Live Drum Racks (<strong>.adg</strong>).', fr: 'Pas besoin de repartir de zéro. Importez dans votre MPC les kits que vous avez déjà construits ailleurs : kits natifs Akai <strong>.xpm</strong>, Native Instruments Maschine (<strong>.mxgrp</strong>, programmes Kitmaker et Maschine) et Ableton Live Drum Racks (<strong>.adg</strong>).', zh: '无需从零开始。把你在其他平台已经搭建好的套件导入 MPC：原生 Akai <strong>.xpm</strong> 套件、Native Instruments Maschine（<strong>.mxgrp</strong>、Kitmaker 及 Maschine 程序）以及 Ableton Live Drum Rack（<strong>.adg</strong>）。', ru: 'Не нужно начинать с нуля. Перенесите в MPC киты, уже собранные в других программах: нативные Akai <strong>.xpm</strong>, Native Instruments Maschine (<strong>.mxgrp</strong>, программы Kitmaker и Maschine) и Ableton Live Drum Racks (<strong>.adg</strong>).' },
    'product.feature1.li1': { en: 'Just drag in the file: the program finds the linked audio samples on its own, even searching your Ableton library automatically.', it: 'Basta trascinare il file: il programma trova da solo i sample audio collegati, cercando automaticamente anche nella tua libreria Ableton.', es: 'Solo tienes que arrastrar el archivo: el programa encuentra por sí solo los samples de audio vinculados, buscando automáticamente incluso en tu librería de Ableton.', de: 'Einfach die Datei hineinziehen: Das Programm findet die verknüpften Audio-Samples selbstständig — es durchsucht dafür sogar automatisch deine Ableton-Bibliothek.', fr: 'Il suffit de glisser le fichier : le programme retrouve seul les samples audio liés, en recherchant même automatiquement dans votre librairie Ableton.', zh: '只需拖入文件：程序会自动找到关联的音频样本，甚至会自动搜索你的 Ableton 音色库。', ru: 'Просто перетащите файл: программа сама найдёт связанные аудиосэмплы, при необходимости автоматически проверив вашу библиотеку Ableton.' },
    'product.feature1.li2': { en: 'If something can’t be found, it tells you clearly — it never guesses or mismatches a sample.', it: 'Se qualcosa non viene trovato, te lo dice chiaramente — non indovina mai né sbaglia un sample.', es: 'Si algo no se encuentra, te lo indica claramente — nunca adivina ni confunde un sample.', de: 'Wenn etwas nicht gefunden werden kann, sagt dir das Programm das klar — es rät niemals und verwechselt nie ein Sample.', fr: 'Si quelque chose est introuvable, il vous le signale clairement — il ne devine jamais et ne se trompe jamais de sample.', zh: '如果找不到某个文件，会明确提示你——绝不会随意猜测或错配样本。', ru: 'Если что-то не найдено, программа явно об этом сообщит — она никогда не угадывает и не подменяет сэмплы.' },
    'product.feature1.li3': { en: 'Convert one file at a time, or an entire library folder in one go.', it: 'Converti un file alla volta, oppure un’intera cartella di libreria in un colpo solo.', es: 'Convierte un archivo a la vez, o toda una carpeta de librería de una sola vez.', de: 'Konvertiere eine Datei nach der anderen — oder einen ganzen Bibliotheksordner auf einmal.', fr: 'Convertissez un fichier à la fois, ou tout un dossier de librairie en une seule opération.', zh: '可逐个转换文件，也可一次性转换整个音色库文件夹。', ru: 'Конвертируйте файлы по одному — или всю папку библиотеки за один раз.' },

    'product.feature2.title': { en: 'Generate 16-pad kits in seconds', it: 'Genera kit a 16 pad in pochi secondi', es: 'Genera kits de 16 pads en segundos', de: 'Erzeuge in Sekunden 16-Pad-Kits', fr: 'Générez des kits 16 pads en quelques secondes', zh: '几秒钟生成 16 键垫套件', ru: 'Создавайте 16-пэдовые киты за секунды' },
    'product.feature2.body': { en: 'The heart of the program: build a complete kit from your samples with a single click.', it: 'Il cuore del programma: costruisci un kit completo dai tuoi sample con un solo clic.', es: 'El corazón del programa: crea un kit completo a partir de tus samples con un solo clic.', de: 'Das Herzstück des Programms: Baue mit einem einzigen Klick ein komplettes Kit aus deinen Samples.', fr: 'Le cœur du programme : construisez un kit complet à partir de vos samples en un seul clic.', zh: '这是程序的核心功能：只需一键，即可用你的样本构建完整套件。', ru: 'Сердце программы: соберите полноценный кит из ваших сэмплов одним щелчком.' },
    'product.feature2.li1': { en: 'Point to a specific folder, or draw from your already-organized personal archive for instant generation.', it: 'Indica una cartella specifica, oppure attingi dal tuo archivio personale già organizzato per una generazione istantanea.', es: 'Indica una carpeta específica, o utiliza tu archivo personal ya organizado para una generación instantánea.', de: 'Zeig auf einen bestimmten Ordner — oder greife für die sofortige Erzeugung auf dein bereits organisiertes persönliches Archiv zurück.', fr: 'Indiquez un dossier spécifique, ou puisez dans votre archive personnelle déjà organisée pour une génération instantanée.', zh: '可指定特定文件夹，或直接从已整理好的个人档案中生成，即时完成。', ru: 'Укажите конкретную папку или используйте уже организованный личный архив для мгновенной генерации.' },
    'product.feature2.li2': { en: 'The program recognizes kick, snare, hi-hat, clap, bass, pad, synth and many other categories on its own — even in ambiguous cases — and never fills a pad with the wrong sample just to fill it.', it: 'Il programma riconosce da solo kick, snare, hi-hat, clap, bass, pad, synth e molte altre categorie — anche nei casi ambigui — e non riempie mai un pad con il sample sbagliato solo per riempirlo.', es: 'El programa reconoce por sí solo kick, snare, hi-hat, clap, bass, pad, synth y muchas otras categorías — incluso en casos ambiguos — y nunca llena un pad con el sample equivocado solo por rellenarlo.', de: 'Das Programm erkennt Kick, Snare, Hi-Hat, Clap, Bass, Pad, Synth und viele weitere Kategorien selbstständig — auch in mehrdeutigen Fällen — und füllt niemals einen Pad nur um des Füllens willen mit dem falschen Sample.', fr: 'Le programme reconnaît seul kick, snare, hi-hat, clap, bass, pad, synth et bien d’autres catégories — même dans les cas ambigus — et ne remplit jamais un pad avec le mauvais sample juste pour le remplir.', zh: '程序能自动识别底鼓、军鼓、踩镲、拍手、贝斯、pad、合成器等多种类别——即便在模糊情况下也能准确判断，绝不会为了填满而随意塞入不合适的样本。', ru: 'Программа сама распознаёт кик, снэйр, хай-хэт, клэп, бас, пэд, синт и множество других категорий — даже в неоднозначных случаях — и никогда не заполнит пэд неподходящим сэмплом лишь бы заполнить его.' },
    'product.feature2.li3': { en: 'Search by key too: if your bass, synth or pad samples have the key in the filename (e.g. “Bass_Am.wav”), you can ask the program to populate the kit in a specific key.', it: 'Puoi anche cercare per tonalità: se i tuoi sample di bass, synth o pad hanno la tonalità nel nome del file (es. “Bass_Am.wav”), puoi chiedere al programma di popolare il kit in una tonalità specifica.', es: 'También puedes buscar por tonalidad: si tus samples de bass, synth o pad tienen la tonalidad en el nombre del archivo (p. ej. “Bass_Am.wav”), puedes pedirle al programa que rellene el kit en una tonalidad específica.', de: 'Auch die Suche nach Tonart ist möglich: Wenn deine Bass-, Synth- oder Pad-Samples die Tonart im Dateinamen tragen (z. B. „Bass_Am.wav“), kannst du das Programm bitten, das Kit in einer bestimmten Tonart zu befüllen.', fr: 'Vous pouvez aussi rechercher par tonalité : si vos samples de bass, synth ou pad indiquent la tonalité dans le nom du fichier (ex. « Bass_Am.wav »), vous pouvez demander au programme de remplir le kit dans une tonalité précise.', zh: '还支持按调性搜索：如果你的贝斯、合成器或 pad 样本文件名中包含调性信息（如 “Bass_Am.wav”），可以让程序按指定调性填充套件。', ru: 'Также доступен поиск по тональности: если в названиях файлов бас-, синт- или пэд-сэмплов указана тональность (например, «Bass_Am.wav»), вы можете попросить программу заполнить кит в определённой тональности.' },

    'product.feature3.title': { en: 'Customize every single pad', it: 'Personalizza ogni singolo pad', es: 'Personaliza cada pad', de: 'Passe jeden einzelnen Pad an', fr: 'Personnalisez chaque pad', zh: '自定义每一个键垫', ru: 'Настраивайте каждый пэд' },
    'product.feature3.body': { en: 'Every pad on the grid is fully in your hands.', it: 'Ogni pad della griglia è completamente nelle tue mani.', es: 'Cada pad de la cuadrícula está totalmente en tus manos.', de: 'Jeder Pad im Raster liegt vollständig in deiner Hand.', fr: 'Chaque pad de la grille est entièrement entre vos mains.', zh: '网格上的每一个键垫都由你完全掌控。', ru: 'Каждый пэд в сетке полностью в ваших руках.' },
    'product.feature3.li1': { en: 'Preview a sample with one click before deciding, replace it by dragging a new file or browsing your folders.', it: 'Ascolta in anteprima un sample con un clic prima di decidere, sostituiscilo trascinando un nuovo file o sfogliando le tue cartelle.', es: 'Escucha un sample con un clic antes de decidir, reemplázalo arrastrando un nuevo archivo o explorando tus carpetas.', de: 'Höre dir ein Sample mit einem Klick vorab an, bevor du dich entscheidest, und ersetze es, indem du eine neue Datei hineinziehst oder deine Ordner durchsuchst.', fr: 'Prévisualisez un sample en un clic avant de décider, remplacez-le en glissant un nouveau fichier ou en parcourant vos dossiers.', zh: '决定前可一键试听样本，通过拖拽新文件或浏览文件夹即可替换。', ru: 'Прослушайте сэмпл в один клик перед тем, как решить, замените его, перетащив новый файл или выбрав из папок.' },
    'product.feature3.li2': { en: 'Reroll a single pad, or reroll an entire category at once (e.g. “regenerate all basses”) without going pad by pad.', it: 'Rigenera un singolo pad, oppure un’intera categoria in una volta sola (es. “rigenera tutti i bassi”) senza doverlo fare pad per pad.', es: 'Vuelve a generar un solo pad, o toda una categoría a la vez (p. ej. “regenerar todos los bajos”) sin tener que hacerlo pad por pad.', de: 'Würfle einen einzelnen Pad neu, oder eine ganze Kategorie auf einmal (z. B. „alle Bässe neu generieren“), ohne Pad für Pad vorzugehen.', fr: 'Régénérez un seul pad, ou une catégorie entière en une fois (ex. « régénérer toutes les basses ») sans passer pad par pad.', zh: '可单独重新生成一个键垫，也可一次性重新生成整个类别（如“重新生成所有贝斯”），无需逐一操作。', ru: 'Перегенерируйте один пэд или сразу целую категорию (например, «пересоздать все басы») без необходимости делать это по одному.' },
    'product.feature3.li3': { en: 'Choose loop, one-shot, or leave it open for each pad — and set it for all 16 pads at once instead of one at a time.', it: 'Scegli loop, one-shot, oppure lascia libero ogni pad — e impostalo per tutti i 16 pad in una volta invece che uno alla volta.', es: 'Elige loop, one-shot o déjalo libre para cada pad — y configúralo para los 16 pads a la vez en lugar de uno por uno.', de: 'Wähle für jeden Pad Loop, One-Shot oder offen — und lege das für alle 16 Pads gleichzeitig fest, statt einzeln.', fr: 'Choisissez loop, one-shot ou laissez libre pour chaque pad — et appliquez le réglage aux 16 pads à la fois plutôt qu’un par un.', zh: '可为每个键垫选择循环、单次播放或保持开放——并可一次性为全部 16 个键垫设置，无需逐个操作。', ru: 'Выберите режим loop, one-shot или оставьте открытым для каждого пэда — и примените настройку сразу ко всем 16 пэдам, а не по одному.' },

    'product.feature4.title': { en: 'Save your favorite working layouts', it: 'Salva i tuoi layout di lavoro preferiti', es: 'Guarda tus diseños de trabajo favoritos', de: 'Speichere deine bevorzugten Arbeits-Layouts', fr: 'Enregistrez vos configurations de travail préférées', zh: '保存你喜欢的工作布局', ru: 'Сохраняйте любимые рабочие раскладки' },
    'product.feature4.body': { en: 'Found the perfect role layout for your genre? Save it under any name and recall it whenever you need it. On top of the ready-to-use layouts already included (classic kit, trap, generic drums), your custom layouts stay one menu away, and survive closing and reopening the program.', it: 'Hai trovato il layout di ruoli perfetto per il tuo genere? Salvalo con qualsiasi nome e richiamalo quando ti serve. Oltre ai layout già pronti all’uso inclusi nel programma (kit classico, trap, batteria generica), i tuoi layout personalizzati restano a un menu di distanza e sopravvivono alla chiusura e riapertura del programma.', es: '¿Encontraste el diseño de roles perfecto para tu género? Guárdalo con el nombre que quieras y recupéralo cuando lo necesites. Además de los diseños listos para usar ya incluidos (kit clásico, trap, batería genérica), tus diseños personalizados quedan a un menú de distancia y sobreviven al cerrar y reabrir el programa.', de: 'Das perfekte Rollen-Layout für dein Genre gefunden? Speichere es unter einem beliebigen Namen und rufe es jederzeit wieder auf. Zusätzlich zu den bereits enthaltenen einsatzbereiten Layouts (klassisches Kit, Trap, generisches Schlagzeug) sind deine eigenen Layouts nur ein Menü entfernt und bleiben auch nach dem Schließen und Neustarten des Programms erhalten.', fr: 'Vous avez trouvé la configuration de rôles parfaite pour votre genre ? Enregistrez-la sous n’importe quel nom et rappelez-la à volonté. En plus des configurations prêtes à l’emploi déjà incluses (kit classique, trap, batterie générique), vos configurations personnalisées restent à un menu de distance et survivent à la fermeture et à la réouverture du programme.', zh: '找到了适合你曲风的最佳角色布局？可以任意命名保存，随时调用。除了程序自带的现成布局（经典套件、trap、通用鼓组）外，你的自定义布局也只需一个菜单即可调用，且在关闭重启程序后依然保留。', ru: 'Нашли идеальную раскладку ролей для своего жанра? Сохраните её под любым именем и вызывайте, когда потребуется. Помимо уже включённых готовых раскладок (классический кит, трэп, обычные ударные), ваши собственные раскладки всегда в одном меню и сохраняются после закрытия и повторного запуска программы.' },

    'product.feature5.title': { en: 'Organize your sample library once', it: 'Organizza la tua libreria di sample una volta sola', es: 'Organiza tu librería de samples una sola vez', de: 'Organisiere deine Sample-Bibliothek einmalig', fr: 'Organisez votre librairie de samples une bonne fois pour toutes', zh: '一次性整理你的样本库', ru: 'Организуйте библиотеку сэмплов один раз' },
    'product.feature5.body': { en: 'Instead of repeating the same search every time, build a personal archive: point to the folders where you keep your samples, the program analyzes them once — cataloging the role, type and key of every file — and from then on every kit generation is instant.', it: 'Invece di ripetere la stessa ricerca ogni volta, costruisci un archivio personale: indica le cartelle dove tieni i tuoi sample, il programma le analizza una volta sola — catalogando ruolo, tipo e tonalità di ogni file — e da quel momento ogni generazione di kit è istantanea.', es: 'En lugar de repetir la misma búsqueda cada vez, crea un archivo personal: indica las carpetas donde guardas tus samples, el programa las analiza una sola vez — catalogando el rol, tipo y tonalidad de cada archivo — y a partir de ahí cada generación de kit es instantánea.', de: 'Statt jedes Mal dieselbe Suche zu wiederholen, baue ein persönliches Archiv auf: Zeig auf die Ordner, in denen du deine Samples aufbewahrst, das Programm analysiert sie einmalig — es katalogisiert Rolle, Typ und Tonart jeder Datei — und danach ist jede Kit-Erzeugung sofort erledigt.', fr: 'Plutôt que de répéter la même recherche à chaque fois, constituez une archive personnelle : indiquez les dossiers où vous conservez vos samples, le programme les analyse une seule fois — en cataloguant le rôle, le type et la tonalité de chaque fichier — et dès lors, chaque génération de kit est instantanée.', zh: '无需每次重复搜索，只需建立一次个人档案：指定存放样本的文件夹，程序会一次性分析所有文件——编录每个文件的角色、类型和调性——此后每次生成套件都是即时完成。', ru: 'Вместо того чтобы каждый раз повторять один и тот же поиск, создайте личный архив: укажите папки с сэмплами, программа один раз проанализирует их — каталогизируя роль, тип и тональность каждого файла — и с этого момента каждая генерация кита будет мгновенной.' },
    'product.feature5.li1': { en: 'The program tracks what changes: new folders, or a folder that’s no longer reachable (like a disconnected external drive), are flagged right away.', it: 'Il programma tiene traccia dei cambiamenti: nuove cartelle, o una cartella non più raggiungibile (come un disco esterno scollegato), vengono segnalate subito.', es: 'El programa hace seguimiento de los cambios: las carpetas nuevas, o una carpeta que ya no es accesible (como un disco externo desconectado), se marcan de inmediato.', de: 'Das Programm verfolgt Änderungen: neue Ordner oder ein nicht mehr erreichbarer Ordner (etwa eine getrennte externe Festplatte) werden sofort gemeldet.', fr: 'Le programme suit les changements : les nouveaux dossiers, ou un dossier devenu inaccessible (comme un disque externe déconnecté), sont signalés immédiatement.', zh: '程序会追踪变化：新增的文件夹，或无法访问的文件夹（如已断开的外置硬盘），都会立即被标记提示。', ru: 'Программа отслеживает изменения: новые папки или папка, ставшая недоступной (например, отключённый внешний диск), сразу помечаются.' },

    'product.feature6.title': { en: 'Batch generation', it: 'Generazione in batch', es: 'Generación por lotes', de: 'Stapelverarbeitung', fr: 'Génération en lot', zh: '批量生成', ru: 'Пакетная генерация' },
    'product.feature6.body': { en: 'Need several variants of the same kind of kit? The batch generator builds and exports multiple distinct kits at once, spreading the available samples across them without ever repeating the same sound in two different kits.', it: 'Ti servono più varianti dello stesso tipo di kit? Il generatore in batch costruisce ed esporta più kit distinti in una volta sola, distribuendo i sample disponibili tra loro senza mai ripetere lo stesso suono in due kit diversi.', es: '¿Necesitas varias variantes del mismo tipo de kit? El generador por lotes crea y exporta varios kits distintos a la vez, distribuyendo los samples disponibles entre ellos sin repetir nunca el mismo sonido en dos kits diferentes.', de: 'Brauchst du mehrere Varianten desselben Kit-Typs? Der Batch-Generator erstellt und exportiert mehrere unterschiedliche Kits auf einmal und verteilt die verfügbaren Samples so, dass derselbe Sound nie in zwei verschiedenen Kits wiederholt wird.', fr: 'Besoin de plusieurs variantes du même type de kit ? Le générateur par lot construit et exporte plusieurs kits distincts à la fois, en répartissant les samples disponibles sans jamais répéter le même son dans deux kits différents.', zh: '需要同一类套件的多个变体？批量生成器可一次构建并导出多个不同的套件，在它们之间合理分配可用样本，绝不会在两个套件中重复使用同一个声音。', ru: 'Нужно несколько вариантов одного и того же типа кита? Пакетный генератор создаёт и экспортирует сразу несколько разных китов, распределяя доступные сэмплы между ними так, чтобы один и тот же звук никогда не повторялся в двух разных китах.' },

    'product.feature7.title': { en: 'Full control over export', it: 'Controllo totale sull’esportazione', es: 'Control total sobre la exportación', de: 'Volle Kontrolle über den Export', fr: 'Contrôle total sur l’exportation', zh: '完全掌控导出流程', ru: 'Полный контроль над экспортом' },
    'product.feature7.li1': { en: 'Choose the kit name and destination folder.', it: 'Scegli il nome del kit e la cartella di destinazione.', es: 'Elige el nombre del kit y la carpeta de destino.', de: 'Wähle Kit-Namen und Zielordner.', fr: 'Choisissez le nom du kit et le dossier de destination.', zh: '自定义套件名称和目标文件夹。', ru: 'Выберите имя кита и папку назначения.' },
    'product.feature7.li2': { en: 'Choose which bank (A–H) of your MPC project the kit should start from.', it: 'Scegli da quale banco (A–H) del tuo progetto MPC deve partire il kit.', es: 'Elige desde qué banco (A–H) de tu proyecto MPC debe empezar el kit.', de: 'Wähle, mit welcher Bank (A–H) deines MPC-Projekts das Kit beginnen soll.', fr: 'Choisissez la banque (A–H) de votre projet MPC à partir de laquelle le kit doit démarrer.', zh: '选择套件在 MPC 工程中从哪个音库（A–H）开始。', ru: 'Выберите, с какого банка (A–H) вашего проекта MPC должен начинаться кит.' },
    'product.feature7.li3': { en: 'Every file is renamed and exported ready to load straight onto your MPC.', it: 'Ogni file viene rinominato ed esportato pronto per essere caricato direttamente sul tuo MPC.', es: 'Cada archivo se renombra y exporta listo para cargarse directamente en tu MPC.', de: 'Jede Datei wird umbenannt und so exportiert, dass sie direkt auf deinen MPC geladen werden kann.', fr: 'Chaque fichier est renommé et exporté prêt à être chargé directement sur votre MPC.', zh: '每个文件都会重命名并导出，可直接加载到你的 MPC 中使用。', ru: 'Каждый файл переименовывается и экспортируется в готовом для загрузки на MPC виде.' },

    'product.buy.title': { en: 'Recover old libraries or build kits from scratch — one program does it all.', it: 'Recupera vecchie librerie o costruisci kit da zero — un solo programma fa tutto.', es: 'Recupera librerías antiguas o crea kits desde cero — un solo programa lo hace todo.', de: 'Alte Bibliotheken retten oder Kits von Grund auf bauen — ein Programm erledigt alles.', fr: 'Récupérez d’anciennes librairies ou créez des kits de zéro — un seul programme fait tout.', zh: '找回旧音色库，或从零开始构建套件——一个程序全部搞定。', ru: 'Восстанавливайте старые библиотеки или собирайте киты с нуля — одна программа делает всё.' },
    'product.buy.desc': { en: 'Whether you need to recover old libraries, build kits from your favorite samples, or quickly produce a batch of consistent variants, MPC Sample · Kit Creator takes you from idea to hardware-ready file.', it: 'Che tu debba recuperare vecchie librerie, costruire kit dai tuoi sample preferiti o produrre rapidamente un batch di varianti coerenti, MPC Sample · Kit Creator ti porta dall’idea al file pronto per l’hardware.', es: 'Ya sea que necesites recuperar librerías antiguas, crear kits a partir de tus samples favoritos o producir rápidamente un lote de variantes coherentes, MPC Sample · Kit Creator te lleva de la idea al archivo listo para el hardware.', de: 'Ob du alte Bibliotheken retten, Kits aus deinen Lieblings-Samples bauen oder schnell einen Stapel stimmiger Varianten erzeugen musst — MPC Sample · Kit Creator bringt dich von der Idee bis zur hardware-fertigen Datei.', fr: 'Que vous ayez besoin de récupérer d’anciennes librairies, de construire des kits à partir de vos samples préférés, ou de produire rapidement un lot de variantes cohérentes, MPC Sample · Kit Creator vous emmène de l’idée au fichier prêt pour le matériel.', zh: '无论你是想找回旧音色库、用喜欢的样本构建套件，还是快速生成一批风格统一的变体，MPC Sample · Kit Creator 都能带你从创意直达可用于硬件的文件。', ru: 'Нужно ли восстановить старые библиотеки, собрать киты из любимых сэмплов или быстро создать серию согласованных вариантов — MPC Sample · Kit Creator проведёт вас от идеи до файла, готового к загрузке в железо.' },
    'product.buy.email': { en: 'Email me', it: 'Scrivimi', es: 'Escríbeme', de: 'Schreib mir', fr: 'Écrivez-moi', zh: '给我发邮件', ru: 'Написать мне' },

    /* gallery aria-labels */
    'product.gallery.prevAria': { en: 'Previous screenshot', it: 'Screenshot precedente', es: 'Captura anterior', de: 'Vorheriger Screenshot', fr: 'Capture précédente', zh: '上一张截图', ru: 'Предыдущий скриншот' },
    'product.gallery.nextAria': { en: 'Next screenshot', it: 'Screenshot successivo', es: 'Siguiente captura', de: 'Nächster Screenshot', fr: 'Capture suivante', zh: '下一张截图', ru: 'Следующий скриншот' },

    /* gallery slides */
    'product.slide1.alt': { en: 'MPC Sample Kit Creator home screen with three cards: Convert Library, Generate Kit, Sound Libraries', it: 'Schermata principale di MPC Sample Kit Creator con tre schede: Convert Library, Generate Kit, Sound Libraries', es: 'Pantalla principal de MPC Sample Kit Creator con tres tarjetas: Convert Library, Generate Kit, Sound Libraries', de: 'Startbildschirm von MPC Sample Kit Creator mit drei Karten: Convert Library, Generate Kit, Sound Libraries', fr: 'Écran d’accueil de MPC Sample Kit Creator avec trois cartes : Convert Library, Generate Kit, Sound Libraries', zh: 'MPC Sample Kit Creator 主界面，包含三个卡片：Convert Library、Generate Kit、Sound Libraries', ru: 'Главный экран MPC Sample Kit Creator с тремя карточками: Convert Library, Generate Kit, Sound Libraries' },
    'product.slide1.title': { en: 'One app, three tools.', it: 'Un’app, tre strumenti.', es: 'Una app, tres herramientas.', de: 'Eine App, drei Tools.', fr: 'Une app, trois outils.', zh: '一款应用，三大工具。', ru: 'Одно приложение — три инструмента.' },
    'product.slide1.caption': { en: 'Convert your old libraries, build a searchable archive of your samples, and generate ready-to-play kits — all from one home screen. Pick a tool and go.', it: 'Converti le tue vecchie librerie, costruisci un archivio ricercabile dei tuoi sample e genera kit pronti da suonare — tutto da un’unica schermata principale. Scegli uno strumento e vai.', es: 'Convierte tus librerías antiguas, crea un archivo buscable de tus samples y genera kits listos para tocar — todo desde una sola pantalla principal. Elige una herramienta y adelante.', de: 'Konvertiere deine alten Bibliotheken, baue ein durchsuchbares Archiv deiner Samples auf und erzeuge spielfertige Kits — alles von einem Startbildschirm aus. Wähle ein Tool und leg los.', fr: 'Convertissez vos anciennes librairies, constituez une archive consultable de vos samples et générez des kits prêts à jouer — le tout depuis un seul écran d’accueil. Choisissez un outil et c’est parti.', zh: '转换旧音色库，建立可搜索的样本档案，并生成随时可用的套件——全部在同一个主界面完成。选好工具，开始使用。', ru: 'Конвертируйте старые библиотеки, стройте архив сэмплов с поиском и создавайте готовые к игре киты — всё с одного главного экрана. Выберите инструмент и начните.' },
    'product.slide2.alt': { en: 'Convert Existing Kits panel with a drop zone for .xpm, .mxgrp and .adg library folders', it: 'Pannello Convert Existing Kits con un’area di trascinamento per cartelle di librerie .xpm, .mxgrp e .adg', es: 'Panel Convert Existing Kits con una zona para soltar carpetas de librerías .xpm, .mxgrp y .adg', de: 'Panel „Convert Existing Kits“ mit einer Ablagezone für .xpm-, .mxgrp- und .adg-Bibliotheksordner', fr: 'Panneau Convert Existing Kits avec une zone de dépôt pour les dossiers de librairies .xpm, .mxgrp et .adg', zh: 'Convert Existing Kits 面板，带有 .xpm、.mxgrp 和 .adg 音色库文件夹的拖放区域', ru: 'Панель Convert Existing Kits с зоной перетаскивания для папок библиотек .xpm, .mxgrp и .adg' },
    'product.slide2.title': { en: 'One import, any library.', it: 'Un’importazione, qualsiasi libreria.', es: 'Una importación, cualquier librería.', de: 'Ein Import, jede Bibliothek.', fr: 'Un import, n’importe quelle librairie.', zh: '一次导入，任意音色库。', ru: 'Один импорт — любая библиотека.' },
    'product.slide2.caption': { en: 'Turn existing Akai (.xpm), Maschine (.mxgrp) or Ableton Drum Rack (.adg) kits into the native .mpcsample format your MPC understands — drop in whole library folders and let it run.', it: 'Trasforma i kit Akai (.xpm), Maschine (.mxgrp) o Ableton Drum Rack (.adg) esistenti nel formato nativo .mpcsample che il tuo MPC capisce — trascina intere cartelle di libreria e lascia lavorare il programma.', es: 'Convierte kits existentes de Akai (.xpm), Maschine (.mxgrp) o Ableton Drum Rack (.adg) al formato nativo .mpcsample que tu MPC entiende — suelta carpetas de librería enteras y deja que funcione.', de: 'Verwandle vorhandene Akai- (.xpm), Maschine- (.mxgrp) oder Ableton-Drum-Rack-Kits (.adg) in das native .mpcsample-Format, das dein MPC versteht — zieh ganze Bibliotheksordner hinein und lass es laufen.', fr: 'Transformez vos kits Akai (.xpm), Maschine (.mxgrp) ou Ableton Drum Rack (.adg) existants au format natif .mpcsample compris par votre MPC — déposez des dossiers de librairie entiers et laissez-le travailler.', zh: '将现有的 Akai（.xpm）、Maschine（.mxgrp）或 Ableton Drum Rack（.adg）套件转换为 MPC 可识别的原生 .mpcsample 格式——直接拖入整个音色库文件夹即可自动处理。', ru: 'Превращайте существующие киты Akai (.xpm), Maschine (.mxgrp) или Ableton Drum Rack (.adg) в нативный формат .mpcsample, понятный вашему MPC — перетащите целые папки библиотек и дайте программе поработать.' },
    'product.slide3.alt': { en: 'Sound Libraries panel with folder list and an Analyze button, showing thousands of samples indexed', it: 'Pannello Sound Libraries con elenco cartelle e pulsante Analyze, con migliaia di sample indicizzati', es: 'Panel Sound Libraries con lista de carpetas y botón Analyze, mostrando miles de samples indexados', de: 'Panel „Sound Libraries“ mit Ordnerliste und Analyze-Schaltfläche, mit tausenden indizierten Samples', fr: 'Panneau Sound Libraries avec liste de dossiers et bouton Analyze, affichant des milliers de samples indexés', zh: 'Sound Libraries 面板，包含文件夹列表和 Analyze 按钮，显示已索引的数千个样本', ru: 'Панель Sound Libraries со списком папок и кнопкой Analyze, показывающая тысячи проиндексированных сэмплов' },
    'product.slide3.title': { en: 'Index your samples once. Generate forever.', it: 'Indicizza i tuoi sample una volta sola. Genera per sempre.', es: 'Indexa tus samples una vez. Genera para siempre.', de: 'Indexiere deine Samples einmal. Generiere für immer.', fr: 'Indexez vos samples une fois. Générez pour toujours.', zh: '一次索引，永久生成。', ru: 'Проиндексируйте сэмплы один раз — генерируйте вечно.' },
    'product.slide3.caption': { en: 'Point at your sample folders and hit Analyze — the app catalogs every sound (role, type, key) so Generate Kit can pull from it instantly, no matter how big the collection. One test run indexed close to 48,000 samples in a single pass.', it: 'Indica le tue cartelle di sample e premi Analyze — l’app catalogherà ogni suono (ruolo, tipo, tonalità) così Generate Kit potrà attingervi all’istante, non importa quanto grande sia la collezione. Un test ha indicizzato quasi 48.000 sample in un solo passaggio.', es: 'Indica tus carpetas de samples y pulsa Analyze — la app cataloga cada sonido (rol, tipo, tonalidad) para que Generate Kit pueda usarlo al instante, sin importar lo grande que sea la colección. Una prueba indexó cerca de 48.000 samples en una sola pasada.', de: 'Zeig auf deine Sample-Ordner und drücke Analyze — die App katalogisiert jeden Sound (Rolle, Typ, Tonart), sodass Generate Kit sofort darauf zugreifen kann, egal wie groß die Sammlung ist. Ein Testlauf indizierte knapp 48.000 Samples in einem einzigen Durchgang.', fr: 'Indiquez vos dossiers de samples et appuyez sur Analyze — l’app catalogue chaque son (rôle, type, tonalité) pour que Generate Kit puisse y puiser instantanément, quelle que soit la taille de la collection. Un test a indexé près de 48 000 samples en une seule passe.', zh: '指定样本文件夹并点击 Analyze——应用会为每个声音编录信息（角色、类型、调性），无论音色库多大，Generate Kit 都能瞬间调用。一次测试运行中，单次索引了近 48,000 个样本。', ru: 'Укажите папки с сэмплами и нажмите Analyze — приложение каталогизирует каждый звук (роль, тип, тональность), чтобы Generate Kit мог мгновенно использовать их, независимо от размера коллекции. В одном тестовом запуске было проиндексировано почти 48 000 сэмплов за один проход.' },
    'product.slide4.alt': { en: 'Generate Kit screen showing a fully populated 16-pad grid with a target key set to F minor', it: 'Schermata Generate Kit con una griglia a 16 pad completamente popolata e tonalità impostata su Fa minore', es: 'Pantalla Generate Kit con una cuadrícula de 16 pads completamente rellena y tonalidad establecida en Fa menor', de: 'Generate-Kit-Bildschirm mit vollständig befülltem 16-Pad-Raster und Zieltonart F-Moll', fr: 'Écran Generate Kit avec une grille de 16 pads entièrement remplie et une tonalité cible réglée sur Fa mineur', zh: 'Generate Kit 界面，16 键垫网格已完全填充，目标调性设为 F 小调', ru: 'Экран Generate Kit с полностью заполненной сеткой из 16 пэдов и целевой тональностью F минор' },
    'product.slide4.title': { en: 'Every pad, filled and ready — or built exactly your way.', it: 'Ogni pad, riempito e pronto — oppure costruito esattamente come vuoi tu.', es: 'Cada pad, listo y preparado — o construido exactamente a tu manera.', de: 'Jeder Pad, gefüllt und bereit — oder ganz nach deinen Vorstellungen gebaut.', fr: 'Chaque pad, rempli et prêt — ou construit exactement à votre façon.', zh: '每个键垫都已填充就绪——或完全按你的方式定制。', ru: 'Каждый пэд заполнен и готов — или собран именно так, как хотите вы.' },
    'product.slide4.caption': { en: 'Generate a full 16-pad kit in one click, in a specific key if you want one, then lock the pads you love and reroll the rest — one at a time or by category. You can also drag a sample straight from a folder on your computer onto any pad. Save the layout, and reuse it on every kit after this one.', it: 'Genera un kit completo a 16 pad con un clic, in una tonalità specifica se vuoi, poi blocca i pad che ti piacciono e rigenera il resto — uno alla volta o per categoria. Puoi anche trascinare un sample direttamente da una cartella del tuo computer su qualsiasi pad. Salva il layout e riutilizzalo su ogni kit successivo.', es: 'Genera un kit completo de 16 pads con un clic, en una tonalidad específica si quieres, luego bloquea los pads que te gustan y vuelve a generar el resto — uno a uno o por categoría. También puedes arrastrar un sample directamente desde una carpeta de tu ordenador a cualquier pad. Guarda el diseño y reutilízalo en cada kit posterior.', de: 'Erzeuge mit einem Klick ein komplettes 16-Pad-Kit, bei Bedarf in einer bestimmten Tonart, sperre dann die Pads, die dir gefallen, und würfle den Rest neu — einzeln oder nach Kategorie. Du kannst auch ein Sample direkt aus einem Ordner auf deinem Computer auf jeden Pad ziehen. Speichere das Layout und nutze es für jedes weitere Kit wieder.', fr: 'Générez un kit complet de 16 pads en un clic, dans une tonalité spécifique si vous le souhaitez, puis verrouillez les pads que vous aimez et régénérez le reste — un par un ou par catégorie. Vous pouvez aussi glisser un sample directement depuis un dossier de votre ordinateur sur n’importe quel pad. Enregistrez la configuration et réutilisez-la pour chaque kit suivant.', zh: '一键生成完整的 16 键垫套件，如需可指定调性，然后锁定你喜欢的键垫，重新生成其余部分——可逐个操作，也可按类别操作。你还可以直接从电脑文件夹将样本拖到任意键垫上。保存布局后，即可在之后的每个套件中重复使用。', ru: 'Создайте полный 16-пэдовый кит одним щелчком, при необходимости в определённой тональности, затем заблокируйте понравившиеся пэды и пересоздайте остальные — по одному или по категориям. Можно также перетащить сэмпл прямо из папки на компьютере на любой пэд. Сохраните раскладку и используйте её для каждого следующего кита.' },

    /* ---------- checkout.html ---------- */
    'checkout.kicker': { en: 'Secure checkout', it: 'Pagamento sicuro', es: 'Pago seguro', de: 'Sicherer Checkout', fr: 'Paiement sécurisé', zh: '安全结账', ru: 'Безопасная оплата' },
    'checkout.title': { en: 'Complete your purchase', it: 'Completa il tuo acquisto', es: 'Completa tu compra', de: 'Schließe deinen Kauf ab', fr: 'Finalisez votre achat', zh: '完成购买', ru: 'Завершите покупку' },
    'checkout.form.emailLabel': { en: 'Email address', it: 'Indirizzo email', es: 'Dirección de correo electrónico', de: 'E-Mail-Adresse', fr: 'Adresse e-mail', zh: '电子邮箱地址', ru: 'Адрес электронной почты' },
    'checkout.form.emailHint': { en: 'Your activation code will be sent here — please double-check it.', it: 'Il tuo codice di attivazione verrà inviato qui — controllalo con attenzione.', es: 'Tu código de activación se enviará aquí — revísalo bien.', de: 'Dein Aktivierungscode wird an diese Adresse gesendet — bitte überprüfe sie sorgfältig.', fr: 'Votre code d’activation sera envoyé à cette adresse — vérifiez-la bien.', zh: '你的激活码将发送至此邮箱——请仔细核对。', ru: 'Код активации будет отправлен на этот адрес — пожалуйста, проверьте его внимательно.' },
    'checkout.payment.title': { en: 'Choose how to buy', it: 'Scegli come acquistare', es: 'Elige cómo comprar', de: 'Wähle deine Zahlungsart', fr: 'Choisissez votre mode d’achat', zh: '选择购买方式', ru: 'Выберите способ покупки' },
    'checkout.payment.paypal.title': { en: 'Get it directly from me', it: 'Ricevilo direttamente da me', es: 'Consíguelo directamente conmigo', de: 'Direkt von mir bekommen', fr: 'Obtenez-le directement auprès de moi', zh: '直接从我这里获取', ru: 'Получите напрямую от меня' },
    'checkout.payment.paypal.subtitle': { en: 'A small discount, no platform fees — paid via Friends & Family. €25 instead of €30.', it: 'Un piccolo sconto, nessuna commissione di piattaforma — pagamento con Amici e familiari. €25 invece di €30.', es: 'Un pequeño descuento, sin comisiones de plataforma — pago con Amigos y familiares. €25 en lugar de €30.', de: 'Ein kleiner Rabatt, keine Plattformgebühren — Zahlung über Freunde & Familie. €25 statt €30.', fr: 'Une petite réduction, sans frais de plateforme — paiement via Famille et amis. €25 au lieu de €30.', zh: '享受小额折扣，无平台手续费——通过“亲友”方式付款。现价 €25，原价 €30。', ru: 'Небольшая скидка, без комиссии платформы — оплата через «Друзья и семья». €25 вместо €30.' },
    'checkout.payment.paypal.noteLabel': { en: 'Your payment note:', it: 'La tua nota di pagamento:', es: 'Tu nota de pago:', de: 'Deine Zahlungsnotiz:', fr: 'Votre note de paiement :', zh: '你的付款备注：', ru: 'Ваше примечание к платежу:' },
    'checkout.payment.paypal.instructions': { en: 'In the PayPal payment note, include the code below together with the email address you’d like your activation code sent to — this part is essential, it’s how we match your payment to your order.', it: 'Nella nota di pagamento PayPal, inserisci il codice qui sotto insieme all’indirizzo email a cui vuoi ricevere il codice di attivazione — questo passaggio è essenziale, è così che abbiniamo il tuo pagamento all’ordine.', es: 'En la nota de pago de PayPal, incluye el código de abajo junto con la dirección de correo a la que quieres que se envíe tu código de activación — este paso es fundamental, así es como emparejamos tu pago con tu pedido.', de: 'Trage in die PayPal-Zahlungsnotiz den untenstehenden Code zusammen mit der E-Mail-Adresse ein, an die dein Aktivierungscode gesendet werden soll — dieser Schritt ist unverzichtbar, so ordnen wir deine Zahlung deiner Bestellung zu.', fr: 'Dans la note de paiement PayPal, indiquez le code ci-dessous ainsi que l’adresse e-mail à laquelle vous souhaitez recevoir votre code d’activation — cette étape est essentielle, c’est ainsi que nous associons votre paiement à votre commande.', zh: '请在 PayPal 付款备注中填写下方代码，并附上你希望接收激活码的邮箱地址——这一步非常重要，我们需要以此将你的付款与订单对应起来。', ru: 'В примечании к платежу PayPal укажите код ниже вместе с адресом электронной почты, на который должен прийти код активации — это обязательный шаг, именно так мы сопоставляем ваш платёж с заказом.' },
    'checkout.payment.paypal.copy': { en: 'Copy', it: 'Copia', es: 'Copiar', de: 'Kopieren', fr: 'Copier', zh: '复制', ru: 'Копировать' },
    'checkout.payment.paypal.cta': { en: 'Continue to PayPal', it: 'Continua su PayPal', es: 'Continuar a PayPal', de: 'Weiter zu PayPal', fr: 'Continuer vers PayPal', zh: '前往 PayPal', ru: 'Перейти в PayPal' },
    'checkout.payment.paypal.copied': { en: 'Copied!', it: 'Copiato!', es: '¡Copiado!', de: 'Kopiert!', fr: 'Copié !', zh: '已复制！', ru: 'Скопировано!' },
    'checkout.payment.bandcamp.title': { en: 'Buy on Bandcamp', it: 'Acquista su Bandcamp', es: 'Compra en Bandcamp', de: 'Auf Bandcamp kaufen', fr: 'Acheter sur Bandcamp', zh: '在 Bandcamp 购买', ru: 'Купить на Bandcamp' },
    'checkout.payment.bandcamp.subtitle': { en: 'Card, Apple Pay & Google Pay checkout.', it: 'Pagamento con carta, Apple Pay e Google Pay.', es: 'Pago con tarjeta, Apple Pay y Google Pay.', de: 'Bezahlung per Karte, Apple Pay & Google Pay.', fr: 'Paiement par carte, Apple Pay et Google Pay.', zh: '支持信用卡、Apple Pay 和 Google Pay 付款。', ru: 'Оплата картой, Apple Pay и Google Pay.' },
    'checkout.payment.bandcamp.cta': { en: 'Continue to Bandcamp', it: 'Continua su Bandcamp', es: 'Continuar a Bandcamp', de: 'Weiter zu Bandcamp', fr: 'Continuer vers Bandcamp', zh: '前往 Bandcamp', ru: 'Перейти на Bandcamp' },
    'checkout.delivery.note': { en: 'Paid through PayPal — your activation code is generated by hand and emailed to you, usually within a few hours. Paid through Bandcamp — your activation code is included automatically with your download, no waiting required.', it: 'Pagando con PayPal — il tuo codice di attivazione viene generato a mano e inviato via email, di solito entro poche ore. Pagando su Bandcamp — il codice di attivazione è incluso automaticamente con il download, senza alcuna attesa.', es: 'Si pagas con PayPal — tu código de activación se genera a mano y se envía por correo, normalmente en pocas horas. Si pagas en Bandcamp — el código de activación se incluye automáticamente con la descarga, sin esperas.', de: 'Bei Zahlung über PayPal — dein Aktivierungscode wird von Hand erstellt und dir per E-Mail zugeschickt, meist innerhalb weniger Stunden. Bei Zahlung über Bandcamp — dein Aktivierungscode ist automatisch im Download enthalten, ganz ohne Wartezeit.', fr: 'Paiement via PayPal — votre code d’activation est généré à la main et envoyé par e-mail, généralement sous quelques heures. Paiement via Bandcamp — votre code d’activation est inclus automatiquement avec votre téléchargement, sans attente.', zh: '通过 PayPal 付款——你的激活码将由人工生成并通过邮件发送，通常几小时内送达。通过 Bandcamp 付款——激活码会随下载自动附上，无需等待。', ru: 'При оплате через PayPal — код активации создаётся вручную и отправляется вам по электронной почте, обычно в течение нескольких часов. При оплате через Bandcamp — код активации автоматически включён в загрузку, без ожидания.' },
    'checkout.help.prefix': { en: 'Code never arrived, or something looks off?', it: 'Il codice non è arrivato, o qualcosa non torna?', es: '¿El código nunca llegó, o algo no cuadra?', de: 'Code nicht angekommen oder etwas stimmt nicht?', fr: 'Le code n’est jamais arrivé, ou quelque chose semble incorrect ?', zh: '没收到激活码，或有其他问题？', ru: 'Код так и не пришёл, или что-то не так?' },
    'checkout.help.link': { en: 'Get in touch', it: 'Scrivimi', es: 'Contáctame', de: 'Kontaktiere mich', fr: 'Contactez-moi', zh: '联系我', ru: 'Свяжитесь со мной' },
    'checkout.summary.priceLabel': { en: 'Price', it: 'Prezzo', es: 'Precio', de: 'Preis', fr: 'Prix', zh: '价格', ru: 'Цена' },
    'checkout.summary.totalLabel': { en: 'Total', it: 'Totale', es: 'Total', de: 'Gesamt', fr: 'Total', zh: '总计', ru: 'Итого' },
    'checkout.summary.footnote': { en: 'Digital product. Your activation code is delivered after payment — no physical shipping.', it: 'Prodotto digitale. Il codice di attivazione viene consegnato dopo il pagamento — nessuna spedizione fisica.', es: 'Producto digital. El código de activación se entrega después del pago — sin envío físico.', de: 'Digitales Produkt. Dein Aktivierungscode wird nach der Zahlung zugestellt — kein Versand.', fr: 'Produit numérique. Votre code d’activation est livré après paiement — aucune expédition physique.', zh: '数字产品。激活码将在付款后发放——无需实体配送。', ru: 'Цифровой продукт. Код активации предоставляется после оплаты — без физической доставки.' }

  };

  function t(key, lang) {
    var entry = TRANSLATIONS[key];
    if (!entry) return key;
    return entry[lang] || entry.en || key;
  }

  function supportedCode(code) {
    for (var i = 0; i < LANGS.length; i++) {
      if (LANGS[i].code === code) return true;
    }
    return false;
  }

  function detectLang() {
    var saved = localStorage.getItem('lang');
    if (saved && supportedCode(saved)) return saved;
    var nav = (navigator.language || navigator.userLanguage || 'en').slice(0, 2).toLowerCase();
    if (supportedCode(nav)) return nav;
    return 'en';
  }

  var currentLang = 'en';

  function applyStaticTranslations(lang) {
    document.documentElement.setAttribute('lang', lang);

    var textEls = document.querySelectorAll('[data-i18n]');
    for (var i = 0; i < textEls.length; i++) {
      textEls[i].textContent = t(textEls[i].getAttribute('data-i18n'), lang);
    }

    var htmlEls = document.querySelectorAll('[data-i18n-html]');
    for (var j = 0; j < htmlEls.length; j++) {
      htmlEls[j].innerHTML = t(htmlEls[j].getAttribute('data-i18n-html'), lang);
    }

    var placeholderEls = document.querySelectorAll('[data-i18n-placeholder]');
    for (var k = 0; k < placeholderEls.length; k++) {
      placeholderEls[k].setAttribute('placeholder', t(placeholderEls[k].getAttribute('data-i18n-placeholder'), lang));
    }

    var ariaEls = document.querySelectorAll('[data-i18n-aria]');
    for (var m = 0; m < ariaEls.length; m++) {
      ariaEls[m].setAttribute('aria-label', t(ariaEls[m].getAttribute('data-i18n-aria'), lang));
    }
  }

  function updateSwitcherUI(lang) {
    var btn = document.getElementById('lang-current-flag');
    if (!btn) return;
    for (var i = 0; i < LANGS.length; i++) {
      if (LANGS[i].code === lang) {
        btn.textContent = LANGS[i].flag;
        break;
      }
    }
    var options = document.querySelectorAll('.lang-option');
    for (var j = 0; j < options.length; j++) {
      options[j].classList.toggle('active', options[j].getAttribute('data-lang') === lang);
    }
  }

  function applyLang(lang) {
    if (!supportedCode(lang)) lang = 'en';
    currentLang = lang;
    localStorage.setItem('lang', lang);
    applyStaticTranslations(lang);
    updateSwitcherUI(lang);
    document.dispatchEvent(new CustomEvent('langchange', { detail: { lang: lang } }));
  }

  function buildSwitcher() {
    var container = document.getElementById('lang-switcher');
    if (!container) return;

    var wrap = document.createElement('div');
    wrap.className = 'lang-switcher';

    var btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'lang-btn';
    btn.setAttribute('aria-label', t('common.langSwitcher', currentLang));
    btn.setAttribute('aria-haspopup', 'true');
    btn.setAttribute('aria-expanded', 'false');
    var flagSpan = document.createElement('span');
    flagSpan.id = 'lang-current-flag';
    flagSpan.textContent = '🇬🇧';
    btn.appendChild(flagSpan);

    var menu = document.createElement('div');
    menu.className = 'lang-menu';
    menu.setAttribute('role', 'menu');

    LANGS.forEach(function (l) {
      var opt = document.createElement('button');
      opt.type = 'button';
      opt.className = 'lang-option';
      opt.setAttribute('data-lang', l.code);
      opt.setAttribute('role', 'menuitem');
      opt.innerHTML = '<span class="lang-flag">' + l.flag + '</span><span class="lang-label">' + l.label + '</span>';
      opt.addEventListener('click', function (e) {
        var code = e.currentTarget.getAttribute('data-lang');
        applyLang(code);
        wrap.classList.remove('open');
        btn.setAttribute('aria-expanded', 'false');
      });
      menu.appendChild(opt);
    });

    btn.addEventListener('click', function (e) {
      e.stopPropagation();
      var isOpen = wrap.classList.toggle('open');
      btn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
    });

    document.addEventListener('click', function () {
      wrap.classList.remove('open');
      btn.setAttribute('aria-expanded', 'false');
    });

    wrap.appendChild(btn);
    wrap.appendChild(menu);
    container.appendChild(wrap);
  }

  buildSwitcher();
  applyLang(detectLang());

  window.I18N = {
    t: t,
    getLang: function () { return currentLang; },
    applyLang: applyLang,
    LANGS: LANGS
  };

})();
